const stocks=[{symbol:'NOVA',name:'Nova Systems',type:'growth',pe:28,growth:'18%',debt:'Low',score:84},{symbol:'HBR',name:'Harbor Financial',type:'value',pe:11,growth:'6%',debt:'Moderate',score:78},{symbol:'SUMT',name:'Summit Health',type:'quality',pe:19,growth:'10%',debt:'Low',score:91},{symbol:'BLUW',name:'BlueWave Tech',type:'growth',pe:32,growth:'22%',debt:'Low',score:88},{symbol:'OAK',name:'Oakline Consumer',type:'value',pe:13,growth:'5%',debt:'Low',score:81},{symbol:'NTH',name:'Northstar Industrial',type:'quality',pe:17,growth:'9%',debt:'Low',score:87}];
const profiles={low:{title:'Stability-Focused',text:'Your selections lean toward reducing volatility and protecting capital. A diversified, conservative mix may fit this learning scenario.',allocation:{'Stocks':30,'Bonds':55,'Cash':15}},medium:{title:'Balanced Builder',text:'Your selections suggest balancing long-term growth with some stability. Diversification remains central to the example.',allocation:{'Stocks':60,'Bonds':30,'Cash':10}},high:{title:'Growth-Focused',text:'Your selections accept more price movement in pursuit of long-term growth. Higher potential return also means higher potential loss.',allocation:{'Stocks':80,'Bonds':15,'Cash':5}}};
const flashcards=[
{q:'A single stock is 45% of your portfolio. What risk stands out?',a:'Concentration risk. One company can have an outsized effect on the portfolio.'},
{q:'You need your invested money next year. What should you consider first?',a:'Time horizon and loss tolerance. Short horizons leave less time to recover from declines.'},
{q:'A stock price falls 20%, but the business thesis is unchanged. What next?',a:'Recheck fundamentals and your thesis instead of reacting to price movement alone.'},
{q:'Two companies have similar growth, but one carries far more debt. Why care?',a:'Higher debt can increase financial risk, especially when earnings weaken or rates rise.'},
{q:'A stock has a very high P/E ratio. What should you investigate?',a:'Whether expected growth and business quality reasonably support the higher valuation.'},
{q:'Why compare a company with peers in the same industry?',a:'Industry comparisons give valuation and operating metrics more useful context.'},
{q:'What is the main benefit of dollar-cost averaging?',a:'It invests on a schedule, reducing the pressure to perfectly time each purchase.'},
{q:'Your portfolio rises until one sector dominates it. What can restore your target mix?',a:'Rebalancing can bring allocations back toward the portfolio targets you selected.'},
{q:'Revenue rises while profit margins keep shrinking. What deserves attention?',a:'Whether costs are rising too quickly and whether that growth is producing durable profit.'},
{q:'A screener gives a stock a high score. Is that enough to buy it?',a:'No. A screener narrows candidates; research and due diligence still come next.'}
];
const $=id=>document.getElementById(id);
function allocationHTML(items){return `<div class="allocation">${Object.entries(items).map(([k,v])=>`<div><b>${k}</b><span class="bar"><i style="width:${v}%"></i></span><span>${v}%</span></div>`).join('')}</div>`}
$('decisionForm').addEventListener('submit',e=>{e.preventDefault();const risk=$('risk').value,p=profiles[risk];const horizon=$('horizon').selectedOptions[0].text,goal=$('goal').selectedOptions[0].text,focus=$('focus').selectedOptions[0].text;$('decisionResult').innerHTML=`<p class="eyebrow">YOUR RESULT</p><h3>${p.title}</h3><p>${p.text}</p>${allocationHTML(p.allocation)}<p><b>Your inputs:</b> ${horizon} • ${goal} • ${focus}</p><small>Example allocation for education only—not a recommendation to buy, sell or hold any security.</small>`});
$('resetDecision').addEventListener('click',()=>{$('decisionForm').reset();$('decisionResult').innerHTML='<p class="eyebrow">YOUR RESULT</p><h3>Ready when you are.</h3><p>Complete the choices and select Analyze. Your result will update here without refreshing.</p>'});
function renderStocks(filter='all'){const list=filter==='all'?stocks:stocks.filter(s=>s.type===filter);$('stockGrid').innerHTML=list.map(s=>`<article class="stock"><div class="ticker"><h3>${s.symbol}</h3><span class="tag">${s.type}</span></div><p>${s.name}</p><div class="metrics"><span><b>${s.pe}</b>P/E</span><span><b>${s.growth}</b>Example growth</span><span><b>${s.debt}</b>Debt</span><span><b>${s.score}/100</b>Demo score</span></div></article>`).join('')}
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderStocks(b.dataset.filter)}));renderStocks();
let cardIndex=0,isFlipped=false;
function renderFlashcard(){const card=flashcards[cardIndex];isFlipped=false;$('flashProgress').textContent=`CARD ${cardIndex+1} OF ${flashcards.length}`;$('flashLabel').textContent='DECISION SCENARIO';$('flashQuestion').textContent=card.q;$('flashcard').classList.remove('flipped');$('prevCard').disabled=cardIndex===0;$('nextCard').disabled=cardIndex===flashcards.length-1}
function flipFlashcard(){const card=flashcards[cardIndex];isFlipped=!isFlipped;$('flashLabel').textContent=isFlipped?'DECISION EXPLANATION':'DECISION SCENARIO';$('flashQuestion').textContent=isFlipped?card.a:card.q;$('flashcard').classList.toggle('flipped',isFlipped)}
$('flashcard').addEventListener('click',flipFlashcard);$('flipCard').addEventListener('click',flipFlashcard);
$('nextCard').addEventListener('click',()=>{if(cardIndex<flashcards.length-1){cardIndex++;renderFlashcard()}});
$('prevCard').addEventListener('click',()=>{if(cardIndex>0){cardIndex--;renderFlashcard()}});
$('restartCards').addEventListener('click',()=>{cardIndex=0;renderFlashcard()});renderFlashcard();
$('newsletterForm').addEventListener('submit',e=>{e.preventDefault();$('newsletterMessage').textContent='Subscribed for this demo. No information was sent or stored.';e.currentTarget.reset()});
$('contactForm').addEventListener('submit',e=>{e.preventDefault();$('contactMessage').textContent=`Thanks, ${$('name').value}. Your demo feedback was received on this page.`;e.currentTarget.reset()});
$('menuButton').addEventListener('click',()=>{const open=$('nav').classList.toggle('open');$('menuButton').setAttribute('aria-expanded',String(open))});document.querySelectorAll('#nav a').forEach(a=>a.addEventListener('click',()=>{$('nav').classList.remove('open');$('menuButton').setAttribute('aria-expanded','false')}));$('year').textContent=new Date().getFullYear();
